apiVersion: v1
kind: Spec
metadata:
  name: test_suite_001
  createdAt: '2026-04-28T18:04:47.583Z'
configuration:
  appId: claut
  image: image
  level: 1
source:
  repository: url
  branch: main
  entrypoint: main
